# ROS Synapse Settings Configuration

[ui]
dark_mode = true
font_size = 12
font_family = "Ubuntu Mono"

[controls]
# Default options for the 3-row control widget
row1_dropdown1_options = ["ros2", "rostopic", "rosnode", "rosservice"]
row1_dropdown1_default = "ros2"
row1_dropdown2_options = ["launch", "run", "pkg", "node"]
row1_dropdown2_default = "launch"

row2_dropdown1_options = ["turtlebot3_bringup", "turtlebot3_navigation2", "turtlebot3_slam"]
row2_dropdown1_default = "turtlebot3_bringup"
row2_dropdown2_options = ["robot.launch.py", "navigation2.launch.py", "slam.launch.py"]
row2_dropdown2_default = "robot.launch.py"

row3_dropdown1_options = ["teleop", "rviz2", "gazebo"]
row3_dropdown1_default = "teleop"
row3_dropdown2_options = ["keyboard", "joy", "twist_mux"]
row3_dropdown2_default = "keyboard"

[ros2]
workspace = "~/ros2_ws"
domain_id = 0
turtlebot3_model = "burger"

[connection]
default_host = "192.168.1.100"
default_username = "ubuntu"
default_port = 22
use_key_auth = true
key_file = "~/.ssh/id_rsa"

[ssh]
# SSH default values
default_address = "ubuntu@raspberrypi"
default_commands = [
    ["watch df", "-h"],
    ["htop", ""]
]

# SSH dropdown options
dropdown1_options = ["ls", "cd", "pwd", "ps", "top", "df", "htop", "watch df", "systemctl", "journalctl", "free", "uptime"]
dropdown2_options = ["-la", "-aux", "-h", "--help", "", "-f", "-m", "-1", "status", "restart", "stop", "start"]